name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install -g npm
      - run: bash .ci/build.sh
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
      - uses: js-soft/ferretdb-github-action@1.0.2
        with:
          ferretdb-telemetry: "enabled"
          ferretdb-port: 27018
      - run: bash .ci/test.sh
